// Database types - will be auto-generated by Supabase CLI later
// For now, we'll define the essential types manually

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      weddings: {
        Row: {
          id: string
          slug: string
          couple_names: string
          partner1_name: string | null
          partner2_name: string | null
          wedding_date: string | null
          venue_name: string | null
          venue_type: string | null
          guest_count: number | null
          owner_id: string
          co_owner_id: string | null
          co_owner_code: string | null
          guest_code: string | null
          primary_color: string
          secondary_color: string
          font_style: string
          payment_status: 'free' | 'paid' | 'trial'
          tier: 'free' | 'starter' | 'professional' | 'ultimate'
          stripe_subscription_id: string | null
          subscription_end_date: string | null
          timeline: any // JSONB
          music_preferences: any // JSONB
          settings: any // JSONB
          spotify_playlist_id: string | null
          spotify_refresh_token: string | null
          is_public: boolean
          allow_guest_submissions: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          couple_names: string
          partner1_name?: string | null
          partner2_name?: string | null
          wedding_date?: string | null
          venue_name?: string | null
          venue_type?: string | null
          guest_count?: number | null
          owner_id: string
          co_owner_id?: string | null
          co_owner_code?: string | null
          guest_code?: string | null
          primary_color?: string
          secondary_color?: string
          font_style?: string
          payment_status?: 'free' | 'paid' | 'trial'
          tier?: 'free' | 'starter' | 'professional' | 'ultimate'
          stripe_subscription_id?: string | null
          subscription_end_date?: string | null
          timeline?: any
          music_preferences?: any
          settings?: any
          spotify_playlist_id?: string | null
          spotify_refresh_token?: string | null
          is_public?: boolean
          allow_guest_submissions?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          couple_names?: string
          partner1_name?: string | null
          partner2_name?: string | null
          wedding_date?: string | null
          venue_name?: string | null
          venue_type?: string | null
          guest_count?: number | null
          owner_id?: string
          co_owner_id?: string | null
          co_owner_code?: string | null
          guest_code?: string | null
          primary_color?: string
          secondary_color?: string
          font_style?: string
          payment_status?: 'free' | 'paid' | 'trial'
          tier?: 'free' | 'starter' | 'professional' | 'ultimate'
          stripe_subscription_id?: string | null
          subscription_end_date?: string | null
          timeline?: any
          music_preferences?: any
          settings?: any
          spotify_playlist_id?: string | null
          spotify_refresh_token?: string | null
          is_public?: boolean
          allow_guest_submissions?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      songs: {
        Row: {
          id: string // Spotify track ID
          title: string
          artist: string
          album: string | null
          album_art: string | null
          preview_url: string | null
          spotify_uri: string
          duration: number | null
          energy: number | null
          bpm: number | null
          valence: number | null
          danceability: number | null
          acousticness: number | null
          genres: string[] | null
          moments: string[] | null
          explicit: boolean
          popularity: number
          audio_features: any | null
          spotify_data: any | null
          added_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          title: string
          artist: string
          album?: string | null
          album_art?: string | null
          preview_url?: string | null
          spotify_uri: string
          duration?: number | null
          energy?: number | null
          bpm?: number | null
          valence?: number | null
          danceability?: number | null
          acousticness?: number | null
          genres?: string[] | null
          moments?: string[] | null
          explicit?: boolean
          popularity?: number
          audio_features?: any | null
          spotify_data?: any | null
          added_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          artist?: string
          album?: string | null
          album_art?: string | null
          preview_url?: string | null
          spotify_uri?: string
          duration?: number | null
          energy?: number | null
          bpm?: number | null
          valence?: number | null
          danceability?: number | null
          acousticness?: number | null
          genres?: string[] | null
          moments?: string[] | null
          explicit?: boolean
          popularity?: number
          audio_features?: any | null
          spotify_data?: any | null
          added_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      guest_submissions: {
        Row: {
          id: string
          wedding_id: string
          song_id: string | null
          guest_name: string
          guest_email: string | null
          table_number: string | null
          song_title: string
          song_artist: string
          song_spotify_id: string | null
          moment: string | null
          dedication: string | null
          status: 'pending' | 'approved' | 'rejected'
          created_at: string
        }
        Insert: {
          id?: string
          wedding_id: string
          song_id?: string | null
          guest_name: string
          guest_email?: string | null
          table_number?: string | null
          song_title: string
          song_artist: string
          song_spotify_id?: string | null
          moment?: string | null
          dedication?: string | null
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string
        }
        Update: {
          id?: string
          wedding_id?: string
          song_id?: string | null
          guest_name?: string
          guest_email?: string | null
          table_number?: string | null
          song_title?: string
          song_artist?: string
          song_spotify_id?: string | null
          moment?: string | null
          dedication?: string | null
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string
        }
      }
      blog_posts: {
        Row: {
          id: string
          slug: string
          title: string
          subtitle: string | null
          content: string
          excerpt: string | null
          meta_title: string | null
          meta_description: string | null
          keywords: string[] | null
          category: string | null
          tags: string[] | null
          featured: boolean
          featured_image: string | null
          images: any
          author_id: string | null
          status: 'draft' | 'published' | 'archived'
          published_at: string | null
          view_count: number
          share_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          title: string
          subtitle?: string | null
          content: string
          excerpt?: string | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          category?: string | null
          tags?: string[] | null
          featured?: boolean
          featured_image?: string | null
          images?: any
          author_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          view_count?: number
          share_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          title?: string
          subtitle?: string | null
          content?: string
          excerpt?: string | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          category?: string | null
          tags?: string[] | null
          featured?: boolean
          featured_image?: string | null
          images?: any
          author_id?: string | null
          status?: 'draft' | 'published' | 'archived'
          published_at?: string | null
          view_count?: number
          share_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      email_captures: {
        Row: {
          id: string
          email: string
          source: string | null
          metadata: any
          subscribed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          source?: string | null
          metadata?: any
          subscribed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          source?: string | null
          metadata?: any
          subscribed?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      upsert_song: {
        Args: {
          p_id: string
          p_title: string
          p_artist: string
          p_album: string | null
          p_album_art: string | null
          p_preview_url: string | null
          p_spotify_uri: string
          p_duration: number | null
          p_energy: number | null
          p_genres: string[] | null
          p_explicit: boolean
          p_spotify_data: any | null
        }
        Returns: Database['public']['Tables']['songs']['Row']
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}